//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiGhost
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categoria
    {
        public Categoria()
        {
            this.Suscripcion = new HashSet<Suscripcion>();
            this.DetEjercicio = new HashSet<DetEjercicio>();
        }
    
        public int Id_Categoria { get; set; }
        public string Tipo { get; set; }
        public string Duracion { get; set; }
        public double Precio { get; set; }
    
        public virtual ICollection<Suscripcion> Suscripcion { get; set; }
        public virtual ICollection<DetEjercicio> DetEjercicio { get; set; }
    }
}
