//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiGhost
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horario
    {
        public Horario()
        {
            this.Instructor = new HashSet<Instructor>();
        }
    
        public int Id_Horario { get; set; }
        public string Turno { get; set; }
    
        public virtual ICollection<Instructor> Instructor { get; set; }
    }
}
