//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiGhost
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instructor
    {
        public Instructor()
        {
            this.DetEjercicio = new HashSet<DetEjercicio>();
        }
    
        public int Id_Instructor { get; set; }
        public string NombreI { get; set; }
        public string ApellidoI { get; set; }
        public Nullable<int> IdHorario { get; set; }
    
        public virtual ICollection<DetEjercicio> DetEjercicio { get; set; }
        public virtual Horario Horario { get; set; }
    }
}
