//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiGhost
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GhostGymApiEntities : DbContext
    {
        public GhostGymApiEntities()
            : base("name=GhostGymApiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Categoria> Categoria { get; set; }
        public DbSet<DetEjercicio> DetEjercicio { get; set; }
        public DbSet<Horario> Horario { get; set; }
        public DbSet<Instructor> Instructor { get; set; }
        public DbSet<Monitoreo1> Monitoreo1 { get; set; }
        public DbSet<Rutinas> Rutinas { get; set; }
        public DbSet<Suscripcion> Suscripcion { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
    }
}
