//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiGhost
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rutinas
    {
        public Rutinas()
        {
            this.DetEjercicio = new HashSet<DetEjercicio>();
        }
    
        public int Id_Rutina { get; set; }
        public string Nivel { get; set; }
        public string Enfoque { get; set; }
    
        public virtual ICollection<DetEjercicio> DetEjercicio { get; set; }
    }
}
